# Additional suppressions for issues detected by Trivy that are not found by OWASP dependency check

vulnerabilities:

  # Leave whitespace at the end of the file for appending suppressions from OWASP dependency check :-)
  # Augment to this file with
  # grep -oE '<(cve|vulnerabilityName)>(CVE|GHSA).*</(cve|vulnerabilityName)>' build-platform/dependency-check-suppress.xml | sed -E 's/<(cve|vulnerabilityName)>(.*)<\/(cve|vulnerabilityName)>/  - id: \2/' >> build-platform/.trivyignore.yaml
